In [1]:
import cv2
import tensorflow
import keras 
from PIL import Image
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

In [2]:
webcam = cv2.VideoCapture(0)

In [3]:
success, image_bgr = webcam.read()
webcam.read()

(True,
 array([[[  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0],
         ...,
         [  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0]],
 
        [[  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0],
         ...,
         [  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0]],
 
        [[  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0],
         ...,
         [  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0]],
 
        ...,
 
        [[  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0],
         ...,
         [  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0]],
 
        [[  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0],
         ...,
         [  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0]],
 
        [[  0, 136,   0],
         [  0, 136,   0],
         [  0, 136,   0],
         ...,
         [  0, 136,  

In [4]:
face_cascade = "haarcascade_frontalface_default.xml"
face_classifier = cv2.CascadeClassifier(face_cascade)
np.set_printoptions(suppress=True)
model = tensorflow.keras.models.load_model('C:/Users/zxcop/Downloads/converted_keras/keras_model.h5')
size = (224, 224)

In [ ]:
while True:
  success, image_bgr = webcam.read()
  image_org = image_bgr.copy()
  image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
  image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)
  faces = face_classifier.detectMultiScale(image_bw)
  for face in faces:
    x, y, w, h = face
    cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    image = cface_rgb
    image = ImageOps.fit(image, size, Image.ANTIALIAS)
    image_array = np.asarray(image)
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    data[0] = normalized_image_array
    prediction = model.predict(data)
    print(prediction)
    if prediction[0][0] > prediction[0][1]:
      cv2.putText(image_bgr,'Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,0),2)
      cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
    else:
      cv2.putText(image_bgr,'Non-Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),2)
      cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,0,255), 2)
 
  cv2.imshow("Mask Detection", image_bgr)
  cv2.waitKey(1)

[[0.56651926 0.43348077]]
[[0.980271   0.01972908]]
[[0.7284112  0.27158874]]
[[0.00000855 0.9999914 ]]
[[0.00000006 1.        ]]
[[0.00000001 1.        ]]
[[0.00000001 1.        ]]
[[0.00000009 0.9999999 ]]
[[0.00001335 0.99998665]]
[[0.0000043 0.9999957]]
[[0.00005642 0.9999436 ]]
[[0.00001868 0.9999813 ]]
[[0.00001443 0.9999856 ]]
[[0.00000945 0.9999906 ]]
[[0.00000945 0.9999906 ]]
[[0.00002161 0.9999784 ]]
[[0.00000772 0.99999225]]
[[0.00000573 0.9999943 ]]
[[0.00000928 0.9999907 ]]
[[0.00000085 0.99999917]]
[[0.00000133 0.9999987 ]]
[[0.00000132 0.9999987 ]]
[[0.00000215 0.99999785]]
[[0.00000013 0.9999999 ]]
[[0.00000064 0.9999994 ]]
[[0.00000197 0.999998  ]]
[[0.00000502 0.999995  ]]
[[0.36018255 0.6398174 ]]
[[0.00001915 0.9999808 ]]
[[0.00001684 0.9999832 ]]
[[0.00000048 0.9999995 ]]
[[0.00000127 0.9999987 ]]
[[0.00002743 0.9999726 ]]
[[0.00003822 0.99996173]]
[[0.00003822 0.99996173]]
[[0.00000039 0.99999964]]
[[0.00000021 0.99999976]]
[[0.00000078 0.99999917]]
[[0.00001448 0